### ISSUE TITLE
Error in installation. Could not find the module named socksipyhandler

### ISSUE THREAD

**Issue by NickDee96** [erdiaker/torrequest#12]
Here's the output

Collecting torrequests
  Using cached https://files.pythonhosted.org/packages/b1/58/b736a9ba42381287dddda3c792985e0fb6020b7e26b69e96c17c100a35de/torrequests-1.1.10.zip
Collecting requests==2.13.0 (from torrequests)
  Using cached https://files.pythonhosted.org/packages/7e/ac/a80ed043485a3764053f59ca92f809cc8a18344692817152b0e8bd3ca891/requests-2.13.0-py2.py3-none-any.whl
Collecting requesocks==0.10.8 (from torrequests)
  Using cached https://files.pythonhosted.org/packages/2b/33/0ecebf3903181cd74d9ff885da4029f59e5f61c99dc66f39c5a170a66d27/requesocks-0.10.8.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mumer\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mumer\\AppData\\Local\\Temp\\pip-install-gunnbal3\\requesocks\\setup.py'"'"'; __file__='"'"'C:\\Users\\mumer\\AppData\\Local\\Temp\\pip-install-gunnbal3\\requesocks\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\mumer\AppData\Local\Temp\pip-install-gunnbal3\requesocks\
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mumer\AppData\Local\Temp\pip-install-gunnbal3\requesocks\setup.py", line 6, in <module>
        import requesocks
      File "C:\Users\mumer\AppData\Local\Temp\pip-install-gunnbal3\requesocks\requesocks\__init__.py", line 26, in <module>
        from .models import Request, Response
      File "C:\Users\mumer\AppData\Local\Temp\pip-install-gunnbal3\requesocks\requesocks\models.py", line 18, in <module>
      File "C:\Users\mumer\AppData\Local\Temp\pip-install-gunnbal3\requesocks\requesocks\packages\__init__.py", line 3, in <module>
        from . import urllib3
      File "C:\Users\mumer\AppData\Local\Temp\pip-install-gunnbal3\requesocks\requesocks\packages\urllib3\__init__.py", line 16, in <module>
        from .connectionpool import (
      File "C:\Users\mumer\AppData\Local\Temp\pip-install-gunnbal3\requesocks\requesocks\packages\urllib3\connectionpool.py", line 65, in <module>
        from .packages import socksipy
      File "C:\Users\mumer\AppData\Local\Temp\pip-install-gunnbal3\requesocks\requesocks\packages\urllib3\packages\socksipy\__init__.py", line 2, in <module>
        import socksipyhandler
    ModuleNotFoundError: No module named 'socksipyhandler'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

**Comment by monkphx** [comment]
I have the same problem , Have you fixed?

**Comment by yaitza** [comment]
me too！

**Comment by NikDy** [comment]
I have same problem, trying to instlal torrequests via pip on Windows. Solved by manualy intall torrequest.py in python packages directory. 
Just copy torrequest.py to .../python3x/lib/site-packages
